# Generated by Django 4.2.4 on 2023-08-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='bodyText',
            new_name='body_text',
        ),
    ]
